export const defaultConfig = Object.freeze({
  runtime: {
    mode: 'backtest',
    logLevel: 'info',
    loopIntervalMs: 60_000,
    idleIntervalMs: 300_000,
    startupWarmup: true,
    symbols: null,
  },
  market: {
    timezone: 'America/New_York',
    sessionMode: 'regular',
    openMinutes: 9 * 60 + 30,
    closeMinutes: 16 * 60,
    preCloseMinutes: 10,
    noTradeOpenMinutes: 10,
    closedDates: [],
  },
  storage: {
    rootDir: 'storage',
    cacheDir: 'storage/cache',
    configsDir: 'storage/configs',
    datasetsDir: 'storage/datasets',
    reportsDir: 'storage/reports',
    runsDir: 'storage/runs',
    snapshotsDir: 'storage/snapshots',
  },
  alpaca: {
    enabled: true,
    paper: true,
    brokerUrl: 'https://paper-api.alpaca.markets/v2',
    dataUrl: 'https://data.alpaca.markets/v2',
    feed: 'iex',
    adjustment: 'raw',
    cryptoLocation: 'us',
    maxRetries: 4,
    retryBaseDelayMs: 750,
    retryMaxDelayMs: 5_000,
    keyId: null,
    secretKey: null,
  },
  llm: {
    enabled: false,
    provider: 'ollama',
    model: 'llama3.1:8b',
    baseUrl: 'http://127.0.0.1:11434',
    temperature: 0.1,
    timeoutMs: 30_000,
  },
  news: {
    enabled: true,
    userAgent: 'baptisto-trading-v3/0.1 (+local research runner)',
    timeoutMs: 10_000,
    cacheTtlMs: 15 * 60 * 1000,
    maxItemsPerFeed: 8,
    feeds: [],
  },
  reports: {
    daily: {
      enabled: true,
      outputSubdir: 'daily',
      watchlistSymbols: [],
      maxNewsItemsPerFeed: 5,
      includeLlmAnalysis: true,
      llmTimeoutMs: 120_000,
    },
    backtests: {
      enabled: true,
      outputSubdir: 'backtests',
    },
    runtimeDaily: {
      enabled: true,
      outputSubdir: 'runtime-daily',
    },
  },
  git: {
    dailyAutoCommitEnabled: false,
    includeRuntimeSessionState: true,
    commitMessagePrefix: 'chore(runtime)',
  },
  execution: {
    dryRun: true,
    entryPolicyGuardEnabled: true,
    clampEntrySizeToHeuristic: true,
    openRejectionCooldownMs: 5 * 60 * 1000,
    deterministicEntry: {
      enabled: false,
      allowedSymbols: [],
      blockedSymbols: [],
      allowedAssetClasses: ['crypto'],
      patterns: {
        trendPullbackContinuation: {
          enabled: true,
          allowScoutEntries: false,
          minimumSignalScore: 9,
          minimumContextScore: 4,
          requireMediumTrendConfirmed: true,
          allowMissingCriticalContext: false,
          allowWeakRelatedContext: false,
          allowDegradedRelatedContext: false,
          allowOverextendedContext: false,
          minimumFastRsi: 46,
          maximumFastRsi: 58,
          minimumFastPriceVsSma: -0.0015,
          maximumFastPriceVsSma: 0.0012,
          minimumFastEmaGap: 0.00025,
          minimumMediumEmaGap: 0.001,
          minimumRelatedTrend: -0.002,
          confidenceBoost: 0.1,
          fallbackRequestedSizePct: 0.006,
          requestedSizeScale: 0.45,
          minRequestedSizePct: 0.003,
          maxRequestedSizePct: 0.008,
        },
        breakoutRetest: {
          enabled: false,
          allowScoutEntries: false,
          minimumSignalScore: 8,
          minimumContextScore: 4,
          requireMediumTrendConfirmed: true,
          allowMissingCriticalContext: false,
          allowWeakRelatedContext: false,
          allowDegradedRelatedContext: false,
          allowOverextendedContext: false,
          minimumFastRsi: 49,
          maximumFastRsi: 61,
          minimumFastPriceVsSma: -0.0008,
          maximumFastPriceVsSma: 0.002,
          minimumFastEmaGap: 0.0002,
          minimumMediumEmaGap: 0.0012,
          minimumRelatedTrend: -0.0015,
          minimumShortBars: 16,
          lookbackBars: 18,
          breakoutWindowBars: 6,
          minBreakoutPct: 0.0012,
          minRetestPullbackPct: 0.0004,
          maxRetestDepthPct: 0.0035,
          maxPostBreakoutStretchPct: 0.0045,
          minRecoveryPct: 0.0004,
          minRetestHoldPct: 0,
          confidenceBoost: 0.12,
          fallbackRequestedSizePct: 0.005,
          requestedSizeScale: 0.4,
          minRequestedSizePct: 0.0025,
          maxRequestedSizePct: 0.007,
        },
      },
    },
    cryptoProfitLock: {
      enabled: true,
      minUnrealizedPnlPct: 0.018,
      fastRsiFloor: 74,
      fastEmaGapCeiling: 0,
      fastPriceVsSmaFloor: 0.001,
      mediumWeakMinUnrealizedPnlPct: 0.024,
      mediumRsiCeiling: 42,
      mediumPriceVsSmaCeiling: -0.004,
      mediumEmaGapCeiling: -0.0015,
      fastRsiCeiling: 68,
      fastEmaGapForMediumWeakExitCeiling: 0.001,
      peakActivationUnrealizedPnlPct: 0.028,
      peakGivebackAbsPct: 0.009,
      peakRetainRatioMax: 0.76,
      fastWeakRsiCeiling: 42,
      fastWeakPriceVsSmaCeiling: -0.001,
      fastWeakEmaGapCeiling: -0.0004,
    },
  },
  telemetry: {
    console: {
      enabled: false,
      colors: true,
      preview: false,
    },
  },
  symbols: {
    default: {
      enabled: true,
      assetClass: 'stock',
      strategy: 'llm_long_v1',
      strategyProfile: 'single_stock',
      timeframes: ['1m', '2m', '5m', '10m', '15m', '30m', '1h', '4h', '1d'],
      evaluationTimeframes: ['10s', '30s', '1m', '2m', '5m', '10m'],
      brokerProtection: {
        enabled: true,
        simpleStopLossPct: 0.02,
      },
      risk: {
        maxPositionPct: 0.05,
        maxPortfolioExposurePct: 0.5,
      },
    },
  },
  relatedSymbols: {
    default: [],
  },
});
